name: cd-main.yml
on:
  push:
    branches: [ "main" ]

jobs:
  cd-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Main 서버 로그인 및 이미지 Pull 및 배포
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MAIN_HOST }}
          username: ${{ secrets.MAIN_USER }}
          key: ${{ secrets.MAIN_SSH_KEY }}
          script: |
            cd /home/ubuntu/deploy

#            docker stop ${{ secrets.MAIN_CONTAINER_NAME }} || true
#            docker rm ${{ secrets.MAIN_CONTAINER_NAME }} || true
#            docker pull ${{ secrets.MAIN_DOCKERHUB_USERNAME }}/likelion-recruit-main:latest
#            docker-compose up -d

            ./deploy.sh